name: cicd pipeline

on: 
  workflow_dispatch:


jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: check code
        run: echo "code clone from github"

  build:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: docker build
        run: echo "docker is building"
  test:
    runs-on: ubuntu-latest
    needs: [code,build]
    steps:
      - name: testing
        run: echo "testing docker"
        
