name: vinay

on:
  push:
    branches: [main]
    

jobs:

  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "hello world"

      - name: say to hello to username
        run: echo "$hello user"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: what is the version of python and docker 
        run: docker --version && python --version
       
      
        
